### ISSUE TITLE
Implement writing of non-iso images

### ISSUE THREAD

**Issue by mastersin** [altlinux/ALTMediaWriter#1]

**Comment by Kvel2D** [comment]
92a2332e33c3bf5dda9d39e2de51d72f805e84c8 partially addresses this by providing a formatted command to rootfs.
Launching rootfs from the app itself doesn't seem good. Need to run in terminal to input sudo password, can't track it's progress, can't cancel it properly, so might as well let the user deal with it directly in the terminal.
