### ISSUE TITLE
Limit release summaries to 3 lines

### ISSUE THREAD

**Issue by mastersin** [altlinux/ALTMediaWriter#18]
Descriptions of more than 2-3 lines need to be cut with ellipsis. Or do dynamic expansion of blocks for each image.

![Current application window](https://user-images.githubusercontent.com/61050/85171058-5a12e580-b27f-11ea-8967-22365164d492.png)

**Comment by mastersin** [comment]
And new lines in description need to be replaced with spaces.

**Comment by Kvel2D** [comment]
Closed by eff9132f3f52786cca9881f1409b64e8b59fe5c1
