### ISSUE TITLE
getalt.org doesn't have releases.json

### ISSUE THREAD

**Issue by mastersin** [altlinux/ALTMediaWriter#2]
This means that the app has to use built-in releases.json. Some releases like nightly(rescue) which are updated frequently will fail to load due to out of date md5 sums in releases.json.

**Comment by Kvel2D** [comment]
bb31caef5d1b130aa62d0e6d525a7836dcad3337 added updating MD5SUM's from getalt.org directly, so md5 sums won't be out of date. Still need getalt.org to have an up-to-date releases.json for other info.
