### ISSUE TITLE
Don't choose latest releases of p10

### ISSUE THREAD

**Issue by mastersin** [altlinux/ALTMediaWriter#25]
Latest distributions based on p10 have been released (server, workstation, eduacation):
* http://ftp.altlinux.org/pub/distributions/ALTLinux/p10/images/education/
* http://ftp.altlinux.org/pub/distributions/ALTLinux/p10/images/workstation/
* http://ftp.altlinux.org/pub/distributions/ALTLinux/p10/images/server/

But altmediawriter get p9 images only.

Additional option added on getalt to images yaml files. It's called "status: release" and could be useful for chosing actual images.

```
[getalt]$ ls _site/_data/images/ -1
p10-education.yml
p10-server.yml
p10-workstation.yml
p8-education.yml
p8-server.yml
p8-starterkits.yml
p8-workstation.yml
p9-education.yml
p9-kworkstation.yml
p9-regular.yml
p9-server-v.yml
p9-server.yml
p9-simply.yml
p9-starterkits.yml
p9-workstation.yml

[getalt]$ cat _site/_data/images/p10-server.yml
---

entries:
  - link: https://mirror.yandex.ru/altlinux/p10/images/server/aarch64/alt-server-10.0-aarch64.iso
    platform: p10
    solution: alt-server
    importance: 0
    arch: aarch64
    type: iso
    status: release
    board: ARM64 UEFI (including Baikal-M)

  - link: https://mirror.yandex.ru/altlinux/p10/images/server/ppc64le/alt-server-10.0-ppc64le.iso
    platform: p10
    solution: alt-server
    importance: 0
    arch: ppc64le
    type: iso
    status: release
    board: POWER8/9

  - link: https://mirror.yandex.ru/altlinux/p10/images/server/x86_64/alt-server-10.0-x86_64.iso
    platform: p10
    solution: alt-server
    importance: 1
    index_icon: download-latest
    arch: x86-64
    type: iso
    status: release
```

**Comment by Kvel2D** [comment]
These files are used to know which urls to load:
- https://github.com/altlinux/ALTMediaWriter/blob/master/app/assets/sections_urls.txt
- https://github.com/altlinux/ALTMediaWriter/blob/master/app/assets/images_urls.txt

The way it works now you would have to update urls in these files and build a new version of altmediawriter to load p10 images.

Would be good if getalt.org would host these files so they can be updated there. This way mediawriter won't need to be updated.

What's needed from getalt.org:
getalt.org should host files named something like "altmediawriter_images.txt" and "altmediawriter_urls.txt". Their locations shouldn't change, at least for as long as possible.

What's needed from altmediawriter:
Altmediawriter will get an update to now load those files from getalt.org.
