### ISSUE TITLE
При записи образа текст в окне наезжает друг на друга.

### ISSUE THREAD

**Issue by Andy-Solo** [altlinux/ALTMediaWriter#31]
При записи образа текст в окне наезжает друг на друга. Версия 1.0.2 для Windows.

![Снимок экрана 2022-05-18 115646](https://user-images.githubusercontent.com/59645829/169000507-0939b68d-fdef-4f24-b013-479b16aca19e.png)

**Comment by Kvel2D** [comment]
Closed by 95e5bd3cde747d1fd9c7e2f0ee1d28a35460074e
