### ISSUE TITLE
При загрузке образа иконки наезжают друг на друга

### ISSUE THREAD

**Issue by Sotlef** [altlinux/ALTMediaWriter#32]
Видно из скриншота, что иконки информационных сообщений налезли друг на друга:
![Screenshot_20220521_130754](https://user-images.githubusercontent.com/2727063/169642511-b4384471-8217-419d-b7b4-2b1ba084d3e7.png)

**Comment by Kvel2D** [comment]
Closed by 95e5bd3cde747d1fd9c7e2f0ee1d28a35460074e
