### ISSUE TITLE
broken description in the installer

### ISSUE THREAD

**Issue by Mariafokanova** [altlinux/ALTMediaWriter#33]
Windows 10 Pro
Version 21H2
Assembly 19044.1706

Download link in documentation (https://docs.altlinux.org/ru-RU/alt-simply/9.1/html/alt-simply/ch04s02.html):
https://github.com/altlinux/ALTMediaWriter/releases/latest/download/AMW-setup.exe

Language breaks during installation.
![altmediawriter-2022-05-25 13-58-22](https://user-images.githubusercontent.com/74016580/170236369-375acc2a-eae9-4d87-b7fe-a8d4aa2c4b9f.png)

**Comment by Kvel2D** [comment]
Closed by 9e496efdcd89be2f02f75bc8e891a7660a3f31ad
