### ISSUE TITLE
Language change during process

### ISSUE THREAD

**Issue by Mariafokanova** [altlinux/ALTMediaWriter#34]
Windows 10 Pro
Version 21H2
Assembly 19044.1706

Download link in documentation (https://docs.altlinux.org/ru-RU/alt-simply/9.1/html/alt-simply/ch04s02.html):
https://github.com/altlinux/ALTMediaWriter/releases/latest/download/AMW-setup.exe

English is used inside the interface in Russian
![altmediawriter-2022-05-25 14-01-47](https://user-images.githubusercontent.com/74016580/170236940-fe5f4926-1489-4545-b392-7246546558af.png)

**Comment by Kvel2D** [comment]
Closed by bbbe2e5a238ecd4d3a1c4f17f192e775636cff67
