### ISSUE TITLE
ALT Media Writer портит другие диски

### ISSUE THREAD

**Issue by SteelBird1982** [altlinux/ALTMediaWriter#37]
ALT Media Writer v. 1.0.4-alt1

Выбираем флешку Verbatim 15.5GB
Видим предупреждение, что Запись приведёт к потере всех данных на Verbatim Store N GO(15.5GB)
видим, что выбран нужный ISO
пропускаем(да, вроде как в этом моменте я виноват - проигнорил[не заметил] предупреждение о 6TB, но, блин откуда на флешке 6 TB?!)
ещё раз убеждаемся, что выбран именно Verbatim Store N GO(15.5GB) и теряем все данные на 6TB внешнем диске. сказать, что я в полной прострации - это ничего не сказать!!!!! Я так понимаю, что файловую структуру внешнего HDD уже не восстановить....
![AltMedia](https://user-images.githubusercontent.com/110152477/181430612-bc3fba6a-c705-4e62-af33-bbec7761c1e3.jpg)

дополнено: зато флешка совсем не пострадала....

**Comment by paxa2012** [comment]
![image](https://user-images.githubusercontent.com/32680173/187706022-f0cbfecb-c170-4e6a-a978-f357f601c0f1.png)
как пофиксить?

**Comment by trimechee** [comment]
@ALTMediaWriter

**Comment by catbazilio15** [comment]
Мне помог AOMEI Partition Assistant профессиональная версия. Все восстановил. Крякнутая версия не помогла. Восстановил лицензионной.

**Comment by Fartovjy** [comment]
> ALT Media Writer v. 1.0.4-alt1
> 
> Выбираем флешку Verbatim 15.5GB Видим предупреждение, что Запись приведёт к потере всех данных на Verbatim Store N GO(15.5GB) видим, что выбран нужный ISO пропускаем(да, вроде как в этом моменте я виноват - проигнорил[не заметил] предупреждение о 6TB, но, блин откуда на флешке 6 TB?!) ещё раз убеждаемся, что выбран именно Verbatim Store N GO(15.5GB) и теряем все данные на 6TB внешнем диске. сказать, что я в полной прострации - это ничего не сказать!!!!! Я так понимаю, что файловую структуру внешнего HDD уже не восстановить.... ![AltMedia](https://user-images.githubusercontent.com/110152477/181430612-bc3fba6a-c705-4e62-af33-bbec7761c1e3.jpg)
> 
> дополнено: зато флешка совсем не пострадала....

Как Я Вас понимаю. 6+3+1+1+1+0,5 и всё нажитое непосильным трудом...

**Comment by aikoncrime** [comment]
полностью поддерживаю. выбирал с одной флешки 128 гб исо файл на вторую флешку с 8 гб. все проверил. нажал запись и резко удалилась флешка на 128 из проводника.

**Comment by nas022** [comment]
Это не программа ..... а лютый ПЗДЦ. В процессе записи ев флешку образа(уже было около 80%), возникла необходимость подключить внешний диск. ИТОГ потеря всех данных внешнего SSD, потому что это убогое Г переключилось моментально на внешний SSD. Авторы ALT Media Writer - РУКОЖОПЫ и кретины.

**Comment by Noff1997** [comment]
Проверил воспроизводимость ошибки на Windows 10
ALTMediaWriter 1.0.4-alt1

Сценарии 1
Шаги:
1. Подключить две флешки.
2. Запустить Alt Media Writer
3. Выбрать образ для записи
4. Выбрать ту флешку, которую подключили последней
5. Начать запись.

Результат: Записывается на выбранную флешку
Дополнительно: Вторая подключенная флешка выбралась автоматически

Сценарий 2:
Шаги:
1. Подключить две флешки.
2. Запустить Alt Media Writer
3. Выбрать образ для записи
4. Выбрать ту флешку, которую подключили первой
5. Начать запись.

Результат: Записывается на выбранную флешку

Сценарий 3
1. Подключить одну флешку
2. Запустить Alt Media Writer
3. Выбрать образ для записи
4. Начать запись 
5. Во время записи подключить вторую флешку

Результат: Запись флешки прервалась. Вторая флешка не затронута, не повредилась.

Дополнительно: При возникновении ошибки, текст ошибки написан иероглифами.

**Comment by alxvmr** [comment]
Исправили проблему в версии [1.0.4-alt2](https://github.com/altlinux/ALTMediaWriter/releases/tag/1.0.4-alt2).
