### ISSUE TITLE
text lines are cut off slightly at the right edge

### ISSUE THREAD

**Issue by mastersin** [altlinux/ALTMediaWriter#5]
Resizing the window affects how much is cutoff.

**Comment by Kvel2D** [comment]
Fedora executable from getfedora.org - bug not present.
Fedora built on current win build machine - bug present.
So probably something to do with the build environment on our win machine.

**Comment by Kvel2D** [comment]
Tried compiling on another machine - bug present.
Problem likely related to different Qt version.

**Comment by Kvel2D** [comment]
Appears to be fixed with newest deploy environment, which includes updated Qt.
