### ISSUE TITLE
on mac progress bars for jobs done by helper don't display correctly

### ISSUE THREAD

**Issue by mastersin** [altlinux/ALTMediaWriter#6]
m_progress->setTo() - sets maximum value for progress bar
m_progress->setValue() - sets progress of progress bar
These are called in MacDrive::onReadyRead().

onReadyRead() is called when the helper program prints it's progress to stdout in WriteJob::work()

Currently helper doesn't print while writing, which causes this issue. Writing still happens.

**Comment by Kvel2D** [comment]
giving up on mac
