### ISSUE TITLE
Fails to build on mipsel

### ISSUE THREAD

**Issue by iv-m** [altlinux/ALTMediaWriter#9]
I'm getting the following error when building ALTMediaWriter 0.1-alt1 to Sisyphus for mipsel architecture:

```
g++ -c -pipe -frecord-gcc-switches -Wall -g -O2 -fPIC -DPIC -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DBINDIR=\"/usr/bin\" -DDATADIR=\"/usr/share\" -DLIBEXECDIR=\"/usr/lib/altmediawriter\" -DMEDIAWRITER_VERSION=\"0.1.0-alt1\" -DORIGIN_MEDIAWRITER_NAME=\"ALTMediaWriter\" -DMEDIAWRITER_NAME=\"altmediawriter\" -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -I../lib -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtQuick -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtQml -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtCore -I. -I/usr/lib/qt5/mkspecs/linux-g++ -o main.o main.cpp
releasemanager.h:502:9: error: expected identifier before numeric constant
  502 |         MIPSEL,
releasemanager.h:502:9: error: expected '}' before numeric constant
In file included from drivemanager.h:26,
--
  497 |     enum Id {
releasemanager.h:502:9: error: expected unqualified-id before numeric constant
  502 |         MIPSEL,
```

In fact, `MIPSEL`, `mips` and some other normal words are predefined macros on mipsel. That's ugly, but that's legacy we can't help living with.

**Comment by iv-m** [comment]
In fact, `MIPSEL` preprocessor macro is not defined when you are asking for C++ without GNU extensions (e.g. use `-std=c++14` instead of `-std=gnu++14`, which is the default for gcc9). Unfortunately, Qt5 in Sisyphus was build with `-std=gnu++11` and it seems not trivially possible to force `qmake` to use any other standard: this option is added **after** `QMAKE_CXXFLAGS` contents.

So, I think the best thing can be done is just renaming the value. I tried renaming it to  `MIPS32EL`, and it seems to make the problem go away.

**Comment by Kvel2D** [comment]
Commited a rename on devel.
